version: "2.15"

services:
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    networks:
      - elastic
networks:
  elastic:
    driver: bridge