# Two node elastic cluster docker file
version: "2.15"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    networks:
      - elastic


  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: kib01
    ports:
      - "5601:5601"
    environment:
     - ELASTICSEARCH_HOSTS=["http://es01:9200","http://es02:9200"]
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
